// Open Science Quiz — Fragenpool
// Quellen: Open-Science-Buch (opensciencebuch-git) und MüCOS-Infomodule.
// Format: correct = Array von Indizes; Länge > 1 bedeutet "mehrere Antworten möglich".

window.OS_QUIZ_CATEGORIES = [
  'Open Science Konzepte',
  'Forschungsfragen & Planung',
  'Materialien & Daten',
  'Veröffentlichung',
  'Kommunikation',
  'Praxis an der Universität Münster',
];

window.OS_QUIZ_QUESTIONS = [

  // ---- Open Science Konzepte ----
  {
    id: 'konzepte-1',
    category: 'Open Science Konzepte',
    difficulty: 'mittel',
    question: 'Fecher & Friesike (2014) unterscheiden fünf „Schools of Thought" des Open-Science-Diskurses. Welche der folgenden gehört NICHT dazu?',
    choices: ['Infrastruktur-Schule', 'Mess-Schule (Measurement)', 'Exzellenz-Schule', 'Pragmatik-Schule'],
    correct: [2],
    explanation: 'Die fünf Schools sind: Infrastruktur, Öffentlichkeit (Public), Messbarkeit (Measurement), Demokratie und Pragmatismus. „Exzellenz" ist keine eigenständige Denkschule in diesem Modell.',
  },
  {
    id: 'konzepte-2',
    category: 'Open Science Konzepte',
    difficulty: 'schwer',
    question: 'Manche Open-Science-Facetten gelten mittlerweile als selbstverständliche „Hygienefaktoren" statt als positive Zusatzleistung („Open-Science-Kano-Modell"). Welche Praktik wird im Kursmaterial explizit als Ausnahme genannt, für die das (noch) nicht gilt?',
    choices: ['Open Access', 'Open Data', 'Citizen Science', 'Reproduzierbarer Code'],
    correct: [2],
    explanation: 'Damit Wissenschaft schnell und vertrauenswürdig wachsen kann, müssen Befunde prüfbar sein (Open Access, Open Data, Open Code) — das gilt inzwischen fast als selbstverständlich. Citizen Science wird im Kursmaterial explizit als Facette genannt, für die diese Kano-Logik (noch) nicht zutrifft.',
  },
  {
    id: 'konzepte-3',
    category: 'Open Science Konzepte',
    difficulty: 'schwer',
    question: 'Welche der folgenden gehören zu den vier Mertonschen Normen der Wissenschaft? (Mehrere Antworten möglich.)',
    choices: ['Universalismus', 'Autonomie', 'Organisierter Skeptizismus', 'Desinteressiertheit', 'Exzellenz', 'Kommunismus (gemeinsamer Wissensbesitz)'],
    correct: [0, 2, 3, 5],
    explanation: 'Robert Mertons vier Normen sind Kommunismus (wissenschaftliches Wissen gehört allen Forschenden gemeinsam), Universalismus, Desinteressiertheit und organisierter Skeptizismus. „Autonomie" und „Exzellenz" werden in Open-Science-Debatten zwar oft diskutiert, gehören aber nicht zu diesen vier Normen.',
  },
  {
    id: 'konzepte-4',
    category: 'Open Science Konzepte',
    difficulty: 'schwer',
    question: 'Nosek beschreibt eine Abfolge von Schritten, in der sich eine gewünschte Verhaltensänderung in der Wissenschaftskultur durchsetzt. Welcher Schritt kommt direkt NACH „möglich" und VOR „normativ"?',
    choices: ['belohnend', 'einfach', 'notwendig', 'freiwillig'],
    correct: [1],
    explanation: 'Die Reihenfolge lautet: möglich → einfach → normativ → belohnend → notwendig, mit Infrastruktur als Fundament der Pyramide.',
  },
  {
    id: 'konzepte-5',
    category: 'Open Science Konzepte',
    difficulty: 'mittel',
    question: 'Welche Aussage zur „San Francisco Declaration on Research Assessment" (DORA) trifft zu?',
    choices: [
      'DORA fordert, den Journal Impact Factor stärker in Berufungsverfahren zu gewichten.',
      'DORA empfiehlt, journalbezogene Metriken wie den Impact Factor nicht als Proxy für die Qualität einzelner Artikel oder Forschender bei Berufungs-, Förder- oder Einstellungsentscheidungen zu nutzen.',
      'DORA ist ein für alle deutschen Hochschulen verpflichtlicher gesetzlicher Standard.',
      'DORA bezieht sich ausschließlich auf Zeitschriften der Lebenswissenschaften.',
    ],
    correct: [1],
    explanation: 'DORA (seit 2012, mittlerweile über 25.000 Unterzeichnende aus 165 Ländern) empfiehlt explizit, journal-level-Metriken nicht als Ersatz für eine inhaltliche Bewertung einzelner Artikel oder Forschender heranzuziehen.',
  },
  {
    id: 'konzepte-6',
    category: 'Open Science Konzepte',
    difficulty: 'schwer',
    question: 'Was unterscheidet den „TOP Factor" (topfactor.org) rechnerisch vom Journal Impact Factor?',
    choices: [
      'Der TOP Factor ist wie der Impact Factor ein Quotient aus Zitationen und Artikelzahl.',
      'Der TOP Factor ist eine Summe von bis zu 10 Kriterien — kein Quotient. Punkte auf einem Kriterium können fehlende Punkte auf einem anderen kompensieren.',
      'Der TOP Factor misst ausschließlich die statistische Power publizierter Studien.',
      'Der TOP Factor wird nur von den Zeitschriften selbst berechnet, ohne externe Prüfung.',
    ],
    correct: [1],
    explanation: 'Die TOP Guidelines (Nosek et al., 2015) umfassen 10 Kriterien; der TOP Factor ist ihre Summe — anders als der (ebenfalls etwas irreführend benannte) Impact Factor, der ein echter Quotient ist. Das erlaubt eine Kompensation zwischen Kriterien, was methodisch kritisiert wird.',
  },
  {
    id: 'konzepte-7',
    category: 'Open Science Konzepte',
    difficulty: 'leicht',
    question: 'Der Grundsatz „So offen wie möglich, so geschlossen wie nötig" (verankert u. a. in Horizon Europe) beschreibt am ehesten welches Prinzip?',
    choices: [
      'Alle Forschungsdaten müssen ausnahmslos veröffentlicht werden.',
      'Offenheit ist der Standardfall; begründete Ausnahmen (z. B. Datenschutz, laufende Patentanmeldungen, sicherheitsrelevante Aspekte) sind zulässig.',
      'Forschungsdaten dürfen erst nach Ablauf des Urheberrechts geöffnet werden.',
      'Nur Fördermittelgeber dürfen über die Offenheit von Forschungsdaten entscheiden.',
    ],
    correct: [1],
    explanation: 'Das Prinzip macht Offenheit zum Standardfall, lässt aber begründete Ausnahmen zu — etwa aus Datenschutz-, Patent- oder Sicherheitsgründen (z. B. bei kritischer Infrastruktur).',
  },
  {
    id: 'konzepte-8',
    category: 'Open Science Konzepte',
    difficulty: 'leicht',
    question: 'Was beschreibt der Begriff „Dual-Use" in Abwägungen zu Open Science?',
    choices: [
      'Forschungsergebnisse werden parallel bei zwei Zeitschriften eingereicht.',
      'Forschung oder Daten könnten sowohl für nützliche als auch für schädliche bzw. missbräuchliche Zwecke genutzt werden.',
      'Ein Datensatz wird für zwei unabhängige Studien verwendet.',
      'Zwei Personen teilen sich die Erstautor*innenschaft.',
    ],
    correct: [1],
    explanation: 'Dual-Use-Bedenken (z. B. bei Biosicherheits- oder KI-Forschung) sind in wenigen Feldern real relevant, werden aber gelegentlich auch pauschal als Einfallstor genutzt, um Offenheit generell einzuschränken.',
  },

  // ---- Forschungsfragen & Planung ----
  {
    id: 'planung-1',
    category: 'Forschungsfragen & Planung',
    difficulty: 'leicht',
    question: 'Was bezeichnet der Begriff „HARKing"?',
    choices: [
      '„Hypothesizing After the Results are Known" — eine Hypothese wird nachträglich so formuliert, als wäre sie vor der Datenerhebung aufgestellt worden.',
      'Ein statistisches Verfahren zur Korrektur multipler Vergleiche.',
      'Die Kombination mehrerer Einzelstudien in einer Metaanalyse.',
      'Ein spezielles Registrierungsformat für Datenmanagementpläne.',
    ],
    correct: [0],
    explanation: 'HARKing entsteht häufig durch Overfitting: Werden viele Modelle/Analysen an einem Datensatz ausprobiert und im Nachhinein das beste Ergebnis als ursprüngliche Hypothese präsentiert, lässt sich Signal nicht mehr von Rauschen unterscheiden.',
  },
  {
    id: 'planung-2',
    category: 'Forschungsfragen & Planung',
    difficulty: 'mittel',
    question: 'Was ist die Kernaussage der von Simmons, Nelson & Simonsohn (2012) vorgeschlagenen „21-Word Solution"?',
    choices: [
      'Ein Vorschlag zur standardisierten Formulierung von Autor*innenschaft.',
      'Eine kurze Selbstverpflichtungsformel, in der offengelegt wird, wie Stichprobengröße, Datenausschlüsse, Manipulationen und Messungen festgelegt wurden.',
      'Ein 21 Punkte umfassender Kriterienkatalog für FAIR-konforme Datensätze.',
      'Eine Kurzfassung des CRediT-Systems mit 21 Rollen.',
    ],
    correct: [1],
    explanation: 'Wortlaut sinngemäß: „Wir berichten, wie wir die Stichprobengröße festgelegt haben, alle Datenausschlüsse, alle Manipulationen und alle Messungen der Studie."',
  },
  {
    id: 'planung-3',
    category: 'Forschungsfragen & Planung',
    difficulty: 'mittel',
    question: 'Die Metapher vom „Garden of Forking Paths" beschreibt in der Methodendiskussion vor allem:',
    choices: [
      'Die vielen legitimen, aber unkontrolliert genutzten analytischen Entscheidungsmöglichkeiten, die ohne Präregistrierung zu falsch-positiven Befunden führen können.',
      'Die Aufteilung eines Forschungsprojekts in mehrere unabhängige Publikationen.',
      'Die unterschiedlichen Karrierewege nach der Promotion.',
      'Die verschiedenen Peer-Review-Modelle einer Zeitschrift.',
    ],
    correct: [0],
    explanation: 'Eine gute Präregistrierung „raubt Forschenden alle Freiheitsgrade" (Wicherts et al., 2016) und verhindert, dass im Nachhinein der günstigste von vielen möglichen Analysepfaden gewählt wird.',
  },
  {
    id: 'planung-4',
    category: 'Forschungsfragen & Planung',
    difficulty: 'mittel',
    question: 'Wodurch unterscheidet sich Stage 2 von Stage 1 bei einem Registered Report?',
    choices: [
      'In Stage 2 wird erneut über die Relevanz der Fragestellung entschieden.',
      'In Stage 2 prüfen die Gutachtenden nur noch, ob die Studie wie im vorab akzeptierten Plan durchgeführt wurde — nicht, ob die Ergebnisse „interessant" sind.',
      'Stage 2 findet vor der Datenerhebung statt.',
      'Stage 2 ist optional und wird nur bei signifikanten Ergebnissen durchgeführt.',
    ],
    correct: [1],
    explanation: 'Die „in-principle acceptance" nach Stage 1 bindet die Publikationsentscheidung an die Qualität von Fragestellung und Methode statt an das Ergebnis — das beugt Publication Bias vor.',
  },
  {
    id: 'planung-5',
    category: 'Forschungsfragen & Planung',
    difficulty: 'schwer',
    question: 'Laut MüCOS-Infomodul boten zum Erhebungszeitpunkt wie viele Zeitschriften das Registered-Report-Format als reguläre oder Sonderausgaben-Option an?',
    choices: ['12', '89', '340', 'über 3.000'],
    correct: [1],
    explanation: 'Das MüCOS-Infomodul nennt konkret 89 Zeitschriften, die zu diesem Zeitpunkt Registered Reports anboten.',
  },
  {
    id: 'planung-6',
    category: 'Forschungsfragen & Planung',
    difficulty: 'leicht',
    question: 'Wann wird ein Datenmanagementplan (DMP) typischerweise erstellt und wofür wird er genutzt?',
    choices: [
      'Erst nach Abschluss der Datenerhebung, um die Daten zu archivieren.',
      'Vor Projektbeginn — er kann Voraussetzung für eine Drittmittelförderung sein und wird oft zusammen mit dem Förderantrag begutachtet.',
      'Nur bei qualitativen Studien, da quantitative Daten kein Datenmanagement benötigen.',
      'Ausschließlich von der IT-Abteilung, ohne Beteiligung der Forschenden.',
    ],
    correct: [1],
    explanation: 'Ein DMP legt vor Projektstart fest, wie mit Daten und Ergebnissen umgegangen wird, und wird bei vielen Drittmittelgebern als Teil des Förderantrags mitbegutachtet.',
  },
  {
    id: 'planung-7',
    category: 'Forschungsfragen & Planung',
    difficulty: 'schwer',
    question: 'Ein einzelner, exakt spezifizierter Korrelationstest hält die nominelle Falsch-Positiv-Rate von 5% ungefähr ein. Was passiert, wenn stattdessen mehrere naheliegende Analysevarianten (z. B. ein- vs. zweiseitig, Pearson/Spearman/Kendall) ausprobiert und nur der kleinste p-Wert berichtet wird?',
    choices: [
      'Die Falsch-Positiv-Rate bleibt bei 5%, da alle Varianten gültige Tests sind.',
      'Die Falsch-Positiv-Rate kann deutlich über 5% ansteigen — Simulationen zu genau diesem Beispiel zeigen einen Anstieg auf über 10%.',
      'Die Falsch-Positiv-Rate sinkt, weil mehr Tests die statistische Power erhöhen.',
      'Es entsteht kein Problem, solange am Ende nur ein p-Wert berichtet wird.',
    ],
    correct: [1],
    explanation: 'Genau das ist die Gefahr unspezifizierter Analysepläne bzw. „researcher degrees of freedom" — je mehr Freiheitsgrade bei Datensammlung und -aufbereitung genutzt werden, desto stärker steigt die tatsächliche Falsch-Positiv-Rate über die nominellen 5%.',
  },
  {
    id: 'planung-8',
    category: 'Forschungsfragen & Planung',
    difficulty: 'leicht',
    question: 'Wie ist „statistische Power" korrekt definiert?',
    choices: [
      'Die Wahrscheinlichkeit, einen tatsächlich existierenden Effekt einer bestimmten Größe auch zu entdecken.',
      'Der Anteil signifikanter Ergebnisse in einer Zeitschrift.',
      'Die Wahrscheinlichkeit, dass ein Nullergebnis publiziert wird.',
      'Die Anzahl der Freiheitsgrade eines statistischen Tests.',
    ],
    correct: [0],
    explanation: 'Statistische Power ist die Wahrscheinlichkeit, einen real existierenden Effekt einer bestimmten Größe mit dem gewählten Studiendesign auch statistisch zu entdecken.',
  },
  {
    id: 'planung-9',
    category: 'Forschungsfragen & Planung',
    difficulty: 'schwer',
    question: '72 Forschende schlugen 2018 (Benjamin et al.) vor, das konventionelle Signifikanzniveau für NEUE Entdeckungen zu verschärfen. Von welchem auf welchen Wert?',
    choices: ['von 5% auf 0,5%', 'von 1% auf 0,1%', 'von 10% auf 5%', 'von 5% auf 1%'],
    correct: [0],
    explanation: 'Der Vorschlag lautete, das Signifikanzniveau für neue Befunde von 5% auf 0,5% zu senken, um die Rate falsch-positiver Entdeckungen zu reduzieren.',
  },

  // ---- Materialien & Daten ----
  {
    id: 'materialien-1',
    category: 'Materialien & Daten',
    difficulty: 'leicht',
    question: 'In den FAIR-Prinzipien für Forschungsdaten steht das „A" für „Accessible". Was bedeutet das konkret laut MüCOS-Infomodul?',
    choices: [
      'Daten müssen archiviert, aber nicht öffentlich zugänglich sein.',
      'Daten können öffentlich und ohne Kosten geöffnet werden.',
      'Daten dürfen nur von autorisierten Personen gelesen werden.',
      'Daten müssen mit einem ausführlichen Kommentar versehen sein.',
    ],
    correct: [1],
    explanation: 'FAIR steht für Findable, Accessible, Interoperable, Reusable. „Accessible" meint explizit: öffentlich und ohne Kosten zu öffnen.',
  },
  {
    id: 'materialien-2',
    category: 'Materialien & Daten',
    difficulty: 'mittel',
    question: 'Worin unterscheiden sich die CARE-Prinzipien von den FAIR-Prinzipien?',
    choices: [
      'CARE ersetzt FAIR vollständig und macht es überflüssig.',
      'CARE geht über rein technische Kriterien hinaus und betont u. a. den Nutzen für und die Kontrolle durch die von den Daten betroffenen (z. B. indigene) Gemeinschaften.',
      'CARE gilt nur für quantitative, FAIR nur für qualitative Daten.',
      'CARE bezieht sich ausschließlich auf Software, FAIR ausschließlich auf Rohdaten.',
    ],
    correct: [1],
    explanation: 'CARE (u. a. Collective Benefit, Authority to Control, Responsibility, Ethics) wurde speziell für Daten von bzw. über indigene Gemeinschaften entwickelt und ergänzt die eher technischen FAIR-Prinzipien um eine ethisch-politische Dimension — Beispiele im Kurs sind Hochwassergefahrenkarten und Bürger*innenbeteiligung.',
  },
  {
    id: 'materialien-3',
    category: 'Materialien & Daten',
    difficulty: 'schwer',
    question: 'Die TRUST-Prinzipien richten sich — anders als FAIR, das sich auf Daten selbst bezieht — vor allem an wen?',
    choices: [
      'An einzelne Forschende, die ihre eigenen Rohdaten benennen.',
      'An digitale Repositorien und Infrastrukturen, die eine vertrauenswürdige, langfristige Aufbewahrung von Daten sicherstellen sollen (Transparency, Responsibility, User focus, Sustainability, Technology).',
      'An Zeitschriften, die über die Annahme von Registered Reports entscheiden.',
      'An Ethikkommissionen bei der Prüfung von Studienanträgen.',
    ],
    correct: [1],
    explanation: 'Die TRUST-Prinzipien ergänzen FAIR um die Perspektive der Repositorien selbst: Transparency, Responsibility, User focus, Sustainability, Technology.',
  },
  {
    id: 'materialien-4',
    category: 'Materialien & Daten',
    difficulty: 'schwer',
    question: 'In der psychologischen Fachsprache bezeichnet „Replikation" (im Unterschied zu „Reproduktion") typischerweise:',
    choices: [
      'Die erneute Analyse derselben Rohdaten mit demselben Code.',
      'Die erneute Datenerhebung mit neuen Daten, um einen Befund zu überprüfen.',
      'Das bloße Kopieren eines Artikels in ein anderes Repositorium.',
      'Eine rein statistische Simulation ohne empirische Daten.',
    ],
    correct: [1],
    explanation: 'In der Psychologie meint „Reproduktion" das erneute Auswerten derselben Daten (auch „komputationale Reproduzierbarkeit" genannt), während „Replikation" auf neuen Daten beruht. In den Wirtschaftswissenschaften wird „Replication" dagegen oft für beide Fälle verwendet — ein häufiger Quell von Verwirrung zwischen Disziplinen.',
  },
  {
    id: 'materialien-5',
    category: 'Materialien & Daten',
    difficulty: 'leicht',
    question: 'Die „Reproducibility Project: Psychology"-Studie (Open Science Collaboration, 2015) fand, dass ungefähr wie viel Prozent der untersuchten psychologischen Befunde erfolgreich repliziert wurden?',
    choices: ['etwa 90%', 'etwa 50%', 'etwa 10%', 'praktisch 100%'],
    correct: [1],
    explanation: 'Nur rund die Hälfte der überprüften Befunde replizierte erfolgreich — ein zentraler Auslöser der sogenannten Replikationskrise.',
  },
  {
    id: 'materialien-6',
    category: 'Materialien & Daten',
    difficulty: 'mittel',
    question: 'Bei welcher Form der Replikation testen mehrere unabhängige Labore gleichzeitig denselben Befund mit einem identischen, vorab abgestimmten Protokoll?',
    choices: ['Konzeptuelle Replikation', 'Registered Replication Report', 'Interne Replikation', 'Close Replication'],
    correct: [1],
    explanation: 'Eine Registered Replication Report (RRR) koordiniert viele Standorte mit demselben Protokoll gleichzeitig. Close Replication nutzt ähnliche Methoden, aber unabhängig geplant; konzeptuelle Replikation testet dieselbe Hypothese bewusst mit anderen Methoden; interne Replikation erfolgt innerhalb derselben Publikation durch dieselbe Gruppe.',
  },
  {
    id: 'materialien-7',
    category: 'Materialien & Daten',
    difficulty: 'mittel',
    question: 'Was macht der Dienst CODECHECK?',
    choices: [
      'Er prüft automatisiert die sprachliche Qualität von Manuskripten.',
      'Er lässt community-basiert prüfen, ob der Code eines Artikels lauffähig ist und die berichteten Ergebnisse reproduziert — zertifizierte Berichte werden öffentlich (z. B. auf Zenodo) veröffentlicht.',
      'Er vergibt automatisch DOIs für Preprints.',
      'Er ist ein eigenes Peer-Review-Modell für qualitative Forschung.',
    ],
    correct: [1],
    explanation: 'CODECHECK ist ein community-getragener Dienst, der prüft, ob veröffentlichter Code die berichteten Ergebnisse tatsächlich reproduziert; Berichte werden öffentlich zugänglich gemacht.',
  },
  {
    id: 'materialien-8',
    category: 'Materialien & Daten',
    difficulty: 'leicht',
    question: 'Was gehört idealerweise zu einem vollständigen „Replication Package" zu einem quantitativen Artikel?',
    choices: [
      'Nur der finale, aufbereitete Datensatz ohne Code.',
      'Rohdaten (soweit rechtlich/ethisch möglich), Aufbereitungs- und Analysecode sowie ein Codebook, mit denen sich die berichteten Ergebnisse eigenständig reproduzieren lassen.',
      'Ausschließlich das PDF des veröffentlichten Artikels.',
      'Eine Liste aller Ko-Autor*innen mit Kontaktdaten.',
    ],
    correct: [1],
    explanation: 'Ein Replication Package soll es Dritten ermöglichen, die berichteten Ergebnisse ohne Rückfrage bei den Autor*innen nachzuvollziehen — idealerweise „auf Knopfdruck" (Push-Button-Replicability).',
  },
  {
    id: 'materialien-9',
    category: 'Materialien & Daten',
    difficulty: 'leicht',
    question: 'Was bewirken „Open Science Badges" (z. B. für Open Data, Open Materials, Preregistration) auf einem Artikel?',
    choices: [
      'Sie ersetzen den Peer-Review-Prozess vollständig.',
      'Sie kennzeichnen sichtbar, dass bestimmte Open-Science-Praktiken nachprüfbar eingehalten wurden (z. B. Daten mit persistentem Identifier hinterlegt).',
      'Sie werden automatisch vergeben, ohne dass eine Prüfung stattfindet.',
      'Sie zeigen an, wie oft ein Artikel zitiert wurde.',
    ],
    correct: [1],
    explanation: 'Badges signalisieren Leser*innen auf einen Blick, dass geprüfte Kriterien (z. B. dauerhaft verlinkte, offene Daten) erfüllt sind.',
  },
  {
    id: 'materialien-10',
    category: 'Materialien & Daten',
    difficulty: 'leicht',
    question: 'Was regelt die Lizenz, unter der geteilte Forschungsmaterialien veröffentlicht werden (z. B. CC BY, CC0)?',
    choices: [
      'Ob und wie Materialien von Dritten genannt, verändert oder kommerziell genutzt werden dürfen.',
      'Ob die Daten FAIR-konform sind.',
      'Wie lange ein Repositorium die Daten mindestens speichern muss.',
      'Ob ein Peer-Review-Verfahren nötig ist.',
    ],
    correct: [0],
    explanation: 'Lizenzen regeln Nennungspflicht, Bearbeitungs- und kommerzielle Nutzungsrechte — unabhängig davon, ob die Daten FAIR sind oder wie lange sie archiviert werden.',
  },

  // ---- Veröffentlichung ----
  {
    id: 'veroeffentlichung-1',
    category: 'Veröffentlichung',
    difficulty: 'schwer',
    question: 'Bei welchem Open-Access-Typ fallen für die Autor*innen keine Publikationsgebühren an UND die Artikel sind sofort frei verfügbar?',
    choices: ['Gold Open Access', 'Diamond Open Access', 'Hybrid Open Access', 'Green Open Access (über eine Moving Wall)'],
    correct: [1],
    explanation: 'Diamond Open Access: sofort frei verfügbar, keine Article Processing Charges. Bei Gold OA zahlen die Autor*innen; Hybrid ist abo-basiert mit optionaler Freischaltung; eine Moving Wall setzt eine Embargofrist voraus.',
  },
  {
    id: 'veroeffentlichung-2',
    category: 'Veröffentlichung',
    difficulty: 'mittel',
    question: 'Was bezeichnet „Green Open Access"?',
    choices: [
      'Ein Zeitschriftenmodell, bei dem Autor*innen für sofortige freie Verfügbarkeit bezahlen.',
      'Das Selbstarchivieren einer (oft der akzeptierten Manuskript-)Version durch die Autor*innen — auf der eigenen Website, im institutionellen Repositorium oder einem Preprint-Server, unabhängig vom Zeitschriftenmodell.',
      'Eine Zeitschrift, die ausschließlich Forschung zu Umweltthemen veröffentlicht.',
      'Ein Peer-Review-Modell mit anonymen Gutachten.',
    ],
    correct: [1],
    explanation: 'Green OA nutzt das Zweitveröffentlichungsrecht der Autor*innen, unabhängig davon, ob die Zeitschrift selbst Open Access anbietet.',
  },
  {
    id: 'veroeffentlichung-3',
    category: 'Veröffentlichung',
    difficulty: 'mittel',
    question: 'Warum wird Hybrid Open Access im MüCOS-Material kritisch bewertet („Double Dipping")?',
    choices: [
      'Weil Autor*innen zweimal begutachtet werden müssen.',
      'Weil die Universität sowohl das Zeitschriften-Abonnement als auch die zusätzliche Open-Access-Gebühr für einzelne Artikel bezahlt.',
      'Weil Hybrid-Zeitschriften grundsätzlich keine Peer-Review durchführen.',
      'Weil sich zwei Autor*innen die Publikationskosten teilen müssen.',
    ],
    correct: [1],
    explanation: 'Double Dipping bedeutet: Die Institution zahlt einmal für das Abonnement der gesamten Zeitschrift und ein zweites Mal, damit einzelne Artikel frei zugänglich werden.',
  },
  {
    id: 'veroeffentlichung-4',
    category: 'Veröffentlichung',
    difficulty: 'leicht',
    question: 'Was ermöglicht der DEAL-Konsortialvertrag deutschen Forschenden?',
    choices: [
      'Kostenlosen Zugang zu allen internationalen Literaturdatenbanken.',
      'Bundesweit ausgehandelte Konditionen, mit denen Forschende ohne zusätzliche individuelle Kosten bei den Vertragsverlagen Open Access publizieren können.',
      'Eine verpflichtende Nutzung ausschließlich von Diamond-Open-Access-Zeitschriften.',
      'Eine automatische Begutachtung im Registered-Report-Format.',
    ],
    correct: [1],
    explanation: 'DEAL bündelt die Verhandlungsmacht deutscher Wissenschaftsorganisationen gegenüber großen Verlagen, um Open-Access-Publizieren ohne individuelle Zusatzkosten zu ermöglichen.',
  },
  {
    id: 'veroeffentlichung-5',
    category: 'Veröffentlichung',
    difficulty: 'mittel',
    question: 'Wofür wurde das CRediT-System (Contributor Roles Taxonomy) eingeführt?',
    choices: [
      'Um die klassische Autor*innenreihenfolge durch eine rein alphabetische Sortierung zu ersetzen.',
      'Um Beiträge zu einer Publikation über standardisierte Rollen differenziert zu dokumentieren, statt nur eine pauschale „Autor*innenschaft" anzugeben — u. a. gegen Ehrenautor*innenschaften.',
      'Um Peer-Reviewer*innen anhand ihrer Gutachten zu benoten.',
      'Um automatisch den Journal Impact Factor einer Zeitschrift zu berechnen.',
    ],
    correct: [1],
    explanation: 'CRediT (Holcombe, 2019) macht einzelne Beiträge sichtbar (z. B. Statistik, Datenerhebung, Konzeption) und erleichtert die faire Bewertung individueller Leistungen.',
  },
  {
    id: 'veroeffentlichung-6',
    category: 'Veröffentlichung',
    difficulty: 'mittel',
    question: 'Bei welchem Peer-Review-Modell ist die Qualitätskontrolle am transparentesten nachvollziehbar?',
    choices: [
      'Gutachten bleiben grundsätzlich vertraulich.',
      'Gutachten werden nur bei Annahme des Artikels veröffentlicht.',
      'Gutachten werden unabhängig vom Ausgang — Annahme oder Ablehnung — veröffentlicht.',
      'Gutachten werden nur auf explizite Anfrage der Autor*innen offengelegt.',
    ],
    correct: [2],
    explanation: 'Nur wenn Gutachten unabhängig vom Ergebnis veröffentlicht werden, ist die Qualitätskontrolle vollständig nachvollziehbar. Das verbreitete „Open Peer Review" (Veröffentlichung nur bei Annahme) gilt im Kursmaterial ausdrücklich als „nur halb passender Name" — abgelehnte Artikel können unrevidiert anderswo eingereicht werden.',
  },
  {
    id: 'veroeffentlichung-7',
    category: 'Veröffentlichung',
    difficulty: 'schwer',
    question: 'Beim Publish-Review-Curate-Modell (PRC), z. B. über Peer Community In (PCI), in welcher Reihenfolge laufen die Schritte ab?',
    choices: [
      'Erst Begutachtung durch eine Zeitschrift, dann Veröffentlichung als Preprint, dann Kuratierung.',
      'Erst Veröffentlichung als Preprint, dann (externe) Begutachtung, dann Kuratierung in thematische Sammlungen durch Zeitschriften.',
      'Erst Kuratierung, dann Begutachtung, dann Veröffentlichung.',
      'Alle drei Schritte laufen zeitgleich ab.',
    ],
    correct: [1],
    explanation: 'PRC kehrt die klassische Reihenfolge um: publish → review → curate. Preprints erhalten über PCI eine positive Begutachtung und können danach ohne weitere Review bei „PCI-freundlichen" Zeitschriften veröffentlicht werden.',
  },
  {
    id: 'veroeffentlichung-8',
    category: 'Veröffentlichung',
    difficulty: 'mittel',
    question: 'Was bedeutet „Results-blind Peer Review"?',
    choices: [
      'Gutachtende kennen weder die Namen der Autor*innen noch der Institution.',
      'Die Begutachtung erfolgt, ohne dass die Gutachtenden die tatsächlichen Ergebnisse kennen — bewertet werden Fragestellung und Methode.',
      'Es findet gar keine Begutachtung statt.',
      'Nur die Ergebnisse, nicht aber Methode oder Einleitung, werden begutachtet.',
    ],
    correct: [1],
    explanation: 'Results-blind Review bewertet die Qualität von Fragestellung und Methodik, bevor die Ergebnisse bekannt sind — ähnlich der Logik von Registered Reports, aber ohne den vollen Stage-1/Stage-2-Prozess.',
  },
  {
    id: 'veroeffentlichung-9',
    category: 'Veröffentlichung',
    difficulty: 'leicht',
    question: 'Was ist PubPeer?',
    choices: [
      'Ein Repositorium für Registered Reports.',
      'Eine Plattform für öffentliche, ggf. anonyme Kommentare zu bereits veröffentlichten Forschungsarbeiten (Post-Publication Peer Review).',
      'Ein automatisches Tool zur FAIR-Prüfung von Datensätzen.',
      'Der offizielle Retraction-Prozess großer Verlage.',
    ],
    correct: [1],
    explanation: 'PubPeer ermöglicht es, nach der Veröffentlichung Kommentare zu einem Artikel zu hinterlassen — teils anonym — und ist so ein Instrument der nachträglichen Qualitätskontrolle.',
  },
  {
    id: 'veroeffentlichung-10',
    category: 'Veröffentlichung',
    difficulty: 'schwer',
    question: 'Welche der folgenden Open-Access-Typen werden im MüCOS-Material aufgrund von Kosten- bzw. Fairness-Bedenken kritisch (negativ) bewertet? (Mehrere Antworten möglich.)',
    choices: ['Diamond', 'Hybrid', 'Moving Wall', 'Promotional', 'Green'],
    correct: [1, 2, 3],
    explanation: 'Diamond und Green gelten als positiv. Hybrid wird wegen „Double Dipping" kritisiert, Moving Wall wegen der Verzögerung des freien Zugangs, und Promotional wird explizit als „Open Washing" bezeichnet.',
  },

  // ---- Kommunikation ----
  {
    id: 'kommunikation-1',
    category: 'Kommunikation',
    difficulty: 'leicht',
    question: 'Was ist eine „Lay Summary"?',
    choices: [
      'Eine verkürzte Zusammenfassung für Fachkolleg*innen.',
      'Eine für Laien verständliche Zusammenfassung eines Forschungsartikels.',
      'Ein Peer-Review-Gutachten.',
      'Ein rechtlicher Haftungsausschluss.',
    ],
    correct: [1],
    explanation: 'Lay Summaries übersetzen Fachartikel in allgemeinverständliche Sprache für eine breitere Öffentlichkeit.',
  },
  {
    id: 'kommunikation-2',
    category: 'Kommunikation',
    difficulty: 'mittel',
    question: 'Welche Klarstellung macht das Kursmaterial ausdrücklich zu Citizen Science?',
    choices: [
      'Citizen Science bedeutet, dass Laien professionelle Forschung eigenständig „widerlegen".',
      'Citizen Science bedeutet, dass Bürger*innen unter Anleitung Einblick in den Forschungsprozess erhalten und zur Wissensgenerierung beitragen — nicht, dass sie klassische Forschung ersetzen oder widerlegen.',
      'Citizen Science ist ausschließlich in den Naturwissenschaften zulässig.',
      'Citizen Science ersetzt die Notwendigkeit eines Ethikantrags.',
    ],
    correct: [1],
    explanation: 'Die Klarstellung richtet sich gegen ein Missverständnis, wonach Citizen Science Laien in Konkurrenz zur „klassischen" Forschung setzt — tatsächlich geht es um begleitete Teilhabe am Forschungsprozess.',
  },
  {
    id: 'kommunikation-3',
    category: 'Kommunikation',
    difficulty: 'leicht',
    question: 'Welches der folgenden ist ein im Kurs genanntes Citizen-Science-Beispiel?',
    choices: [
      'Ein Bürger*innen-Projekt zum ferngesteuerten Betrieb von Weltraumteleskopen (aim-muenster.de).',
      'Ein Peer-Review-Verfahren für studentische Abschlussarbeiten.',
      'Eine automatisierte FAIR-Prüfung von Forschungsdaten.',
      'Ein Zitationsindex für Fachzeitschriften.',
    ],
    correct: [0],
    explanation: 'Weitere genannte Beispiele sind das Liebesbriefarchiv (linguistisch-kulturhistorische Auswertung durch Bürger*innen) und das Portal mitforschen.org.',
  },
  {
    id: 'kommunikation-4',
    category: 'Kommunikation',
    difficulty: 'leicht',
    question: 'Was zeichnet Open Educational Resources (OER) am ehesten aus?',
    choices: [
      'Lehrmaterialien, die kostenlos herunterladbar bzw. frei nutzbar sind (z. B. Bücher, Folien, Erklärvideos).',
      'Ausschließlich staatlich geprüfte Schulbücher.',
      'Lehrmaterialien, die nur an der eigenen Universität verwendet werden dürfen.',
      'Forschungsdaten, die im Unterricht analysiert werden.',
    ],
    correct: [0],
    explanation: 'OER umfasst ein breites Spektrum an Lehrmaterialien, deren gemeinsames Merkmal die freie Zugänglichkeit bzw. Nutzbarkeit ist.',
  },
  {
    id: 'kommunikation-5',
    category: 'Kommunikation',
    difficulty: 'schwer',
    question: 'Welches Spannungsfeld beschreibt das Kursmaterial bei der öffentlichen Kommunikation von Wissenschaftsproblemen (z. B. Replikationskrise)?',
    choices: [
      'Offene Selbstkritik ist intern notwendig, kann aber bei unreflektierter öffentlicher Kommunikation das Vertrauen in Wissenschaft beschädigen — obwohl Selbstkorrektur eigentlich ein Zeichen funktionierender Wissenschaft ist.',
      'Es gibt keinerlei Unterschied zwischen interner und externer Kommunikation.',
      'Öffentliche Kommunikation über Probleme in der Wissenschaft ist grundsätzlich untersagt.',
      'Nur Fachzeitschriften dürfen über Reproduzierbarkeitsprobleme berichten.',
    ],
    correct: [0],
    explanation: 'Die Herausforderung besteht darin, Probleme intern klar zu benennen, ohne dass eine unreflektierte öffentliche Darstellung fälschlich den Eindruck erweckt, Wissenschaft sei grundsätzlich unzuverlässig — dabei ist gerade die Fähigkeit zur Selbstkorrektur ein Vertrauensargument.',
  },
  {
    id: 'kommunikation-6',
    category: 'Kommunikation',
    difficulty: 'mittel',
    question: 'Wie lange garantieren Zenodo bzw. OSF laut Kursmaterial mindestens die Verfügbarkeit archivierter Materialien?',
    choices: ['5 bzw. 10 Jahre', '20 bzw. 50 Jahre', '1 bzw. 2 Jahre', 'unbegrenzt, ohne jede Garantie'],
    correct: [1],
    explanation: 'Zenodo und OSF garantieren laut Kursmaterial die Verfügbarkeit für mindestens 20 bzw. 50 Jahre — relevant auch für die langfristige Verfügbarkeit von OER.',
  },

  // ---- Praxis an der Universität Münster ----
  {
    id: 'praxis-1',
    category: 'Praxis an der Universität Münster',
    difficulty: 'leicht',
    question: 'An wen wenden Sie sich an der Universität Münster bei Fragen zur Präregistrierung oder zu Registered Reports?',
    choices: ['MüCOS', 'Stabsstelle Datenschutz', 'Arbeitsstelle Forschungstransfer', 'Koordination Diversity'],
    correct: [0],
    explanation: 'MüCOS (Münster Center for Open Science) ist Ansprechpartner für Präregistrierung, Registered Reports und weitere Open-Science-Praktiken entlang des Forschungszyklus.',
  },
  {
    id: 'praxis-2',
    category: 'Praxis an der Universität Münster',
    difficulty: 'mittel',
    question: 'Wer ist an der Universität Münster die zentrale Anlaufstelle für Fragen zu Open Data und Forschungsdatenmanagement?',
    choices: ['MüCOS', 'Service Center for Data Management', 'Ethikräte der Fachbereiche', 'Vertrauensperson des Senats'],
    correct: [1],
    explanation: 'Das Service Center for Data Management berät konkret zu Forschungsdatenmanagement, etwa zur FAIR-Aufbereitung von Daten.',
  },
  {
    id: 'praxis-3',
    category: 'Praxis an der Universität Münster',
    difficulty: 'mittel',
    question: 'Verstöße gegen gute wissenschaftliche Praxis (GWP) werden an der Universität Münster von wem untersucht bzw. sanktioniert?',
    choices: ['Der Pressestelle', 'Einer Vertrauensperson bzw. Untersuchungskommission des Senats', 'Dem Prüfungsamt', 'Der Stabsstelle Datenschutz'],
    correct: [1],
    explanation: 'Für Verstöße gegen gute wissenschaftliche Praxis existiert ein geregeltes Verfahren über eine Vertrauensperson bzw. eine Untersuchungskommission des Senats.',
  },
  {
    id: 'praxis-4',
    category: 'Praxis an der Universität Münster',
    difficulty: 'leicht',
    question: 'Wer berät an der Universität Münster zu Fragen der Anonymisierung und zum Datenschutz von Forschungsdaten?',
    choices: ['MüCOS', 'Die Stabsstelle Datenschutz', 'Die Koordination Diversity', 'Die Arbeitsstelle Forschungstransfer'],
    correct: [1],
    explanation: 'Datenschutzrechtliche Fragen zu Forschungsdaten werden von der Stabsstelle Datenschutz geklärt.',
  },
];
